name: Export files

on:
  schedule:
    - cron: "0 2 * * *" # 每天执行
  workflow_dispatch:

jobs:
  convert_conf_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: pip3 install glob2

    - name: Convert Conf Files
      env:
        CN_DNS: ${{ secrets.CN_DNS }}
        THE_DNS: ${{ secrets.THE_DNS }}
      run: python convert.py

    - name: Create Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: converted-files
        path: converted
        overwrite: true

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: 'converted-files'  # 要下载的 Artifact 名称
        path: 'converted'  # 下载 Artifact 后的存储路径

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: converted-files
        path: ./release-artifacts

    - name: Attach to Release
      uses: softprops/action-gh-release@v1
      with:
        #repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: "Released on $(date +%Y%m%d%H%M)"
        tag_name: "$(date +%Y%m%d%H%M)"
        file_glob: true
        files: release-artifacts/*.txt
