name: Export files

on:
  schedule:
    - cron: "0 2 * * *" # 每天执行
  workflow_dispatch:

jobs:
  convert_conf_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: pip3 install glob2

    - name: Convert Conf Files
      env:
        CN_DNS: ${{ secrets.CN_DNS }}
        THE_DNS: ${{ secrets.THE_DNS }}
      run: python convert.py

    - name: Create Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: converted-files
        path: converted
        overwrite: true

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: 'converted-files'  # 要下载的 Artifact 名称
        path: 'converted'  # 下载 Artifact 后的存储路径

    - name: copy file
      run: |
        mkdir txt
        cp converted/* ./txt/

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
      tag_name: v${{ github.run_id }}  # 动态生成唯一标签
      release_name: Release ${{ github.run_id }}
      draft: false
      prerelease: false

    - name: Download Artifact for Release
      uses: actions/download-artifact@v4
      with:
        name: converted-files
        path: ./release-assets

    - name: Upload to Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-assets/converted/*  # 匹配所有构件
        asset_name: converted-files.zip
        asset_content_type: application/zip
