name: Export files

on:
  schedule:
    - cron: "0 2 * * *" # 每天执行
  workflow_dispatch:

jobs:
  convert_conf_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: pip3 install glob2

    - name: Convert Conf Files
      env:
        CN_DNS: ${{ secrets.CN_DNS }}
        THE_DNS: ${{ secrets.THE_DNS }}
      run: python convert.py

    - name: Create Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: converted-files
        path: converted
        overwrite: true

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: 'converted-files'  # 要下载的 Artifact 名称
        path: 'converted'  # 下载 Artifact 后的存储路径

    - name: copy file
      run: |
        mkdir txt
        cp converted/* ./txt/

    - name: Upload # 上传
      uses: softprops/action-gh-release@v2 # 使用第三方actions 上传
      if: startsWith(github.ref, 'refs/tags/') # 仅在tag时上传
      with:
        files: converted/* # 上传的文件
